replicaCount: 1
image:
  repository: <image name>
  pullPolicy: Always
  tag: <image tag>
secretName: <secret name>
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: <ingress domain>
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
